# Generated by Django 2.1.1 on 2018-09-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20180910_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
